### ISSUE TITLE
ブログ拝見しました

### ISSUE THREAD

**Issue by takahashikzn** [hikariru/slack-notification#18]
初めまして、ルート42の高橋と申します。
こちら拝見しました。
https://hikariru.tumblr.com/post/181570632821/%E9%80%80%E8%81%B7%E3%81%97%E3%81%9F
inumeshiさんのTwitterのアカウントを特定できなかった（ググったらいくつかでてきた）ので、
Githubで連絡させて頂きました。すいません。

当社はDocurain( https://docurain.jp )というサービスを運営しているベンチャーです。
エンジニア募集中ですので、もしよろしければ一度会ってお話の機会を頂けますと幸いです。
よろしくお願いします！

(私のTwitterアカウントはこちらです: https://twitter.com/takahashikzn )

**Comment by takahashikzn** [comment]
↑ご連絡がなさそうだったので取り下げます。不躾な連絡、大変失礼致しました。

**Comment by hikariru** [comment]
すみません、見落としておりました。

また、WantedlyのプロフィールからTwitterなどご確認いただけるかと思います。
